version: '3'

services:
  php:
    container_name: rest-api
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    restart: 'always'
    working_dir: '/app'
    volumes: [ '../:/app' ]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NGINX_WEB_ROOT=/app/rest-api/public
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - INFLUXDB_DSN=influxdb://influxdb:8086
    depends_on: ['influxdb']
    ports: [ '80:80' ]

  influxdb:
    image: 'influxdb:1.4'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    environment:
      - INFLUXDB_DB=testdb
    ports: [ '8086:8086' ]

  frontend-app:
    container_name: frontend-app
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    working_dir: '/app'
    volumes: [../frontend-app/:/app]
    ports:
      - 3000:3000

volumes:
  influxdb: